config/routes.rb
Rails.application.routes.draw do 
  match 'site_translations' => 'GoTranslateYourself::SiteTranslations#edit', :as => :site_translations, :method => :get
  match 'site_translations/save' => 'GoTranslateYourself::SiteTranslations#update', :as => :update_site_translations, :method => :post
end

app/models/go_translate_yourself/base_store.rb
require 'yaml'

module GoTranslateYourself
  class BaseStore

    def keys
      if @dev_translations.nil? || Rails.env.development?
        load_dev_translations

        @keys = GoTranslateYourself.locales.collect {|lang| keys_without_prefix.collect {|key| "#{lang}.#{key}"} }.flatten
      end

      @keys
    end

    def default_translation(key)
      load_dev_translations unless @dev_translations
      @dev_translations[key.to_s.gsub(/^[a-z]*\./, "")]
    end

    def keys_without_prefix 
      load_dev_translations unless @dev_translations
      @dev_translations.keys
    end

    protected

    def load_dev_translations
      dev_translations = YAML.load_file(File.join(Rails.root, "config", "locales", "dev.yml"))
      @dev_translations = {}
      flatten_keys(nil, dev_translations["dev"], @dev_translations)
    end

    def flatten_keys(current_key, hash, dest_hash)
      hash.each do |key, value|
        full_key = [current_key, key].compact.join('.')
        if value.kind_of?(Hash)
          flatten_keys full_key, value, dest_hash
        else
          dest_hash[full_key] = ActiveSupport::JSON.encode(value)
        end
      end
    end
  end
end

app/models/go_translate_yourself/mongo_store.rb
module GoTranslateYourself
  class MongoStore < BaseStore
    def initialize(collection)
      @collection = collection
    end

    def []=(key, value)
      collection.update({:_id => key}, {'$set' => {:value => ActiveSupport::JSON.encode(value)}}, :upsert => true, :safe => true)
    end

    def [](key)
      load_dev_translations if Rails.env.development?
      if document = collection.find_one(:_id => key)
        document["value"]
      else
        default_translation(key)
      end
    end

    def clear_database
      collection.drop
    end

    private

    def collection; @collection; end
  end
end

app/models/go_translate_yourself/redis_store.rb
module GoTranslateYourself
  class RedisStore < BaseStore
    def initialize(collection)
      @collection = collection
    end

    def []=(key, value)
      collection.update({:_id => key}, {'$set' => {:value => ActiveSupport::JSON.encode(value)}}, :upsert => true, :safe => true)
    end

    def [](key)
      load_dev_translations if Rails.env.development?
      if document = collection.find_one(:_id => key)
        document["value"]
      else
        default_translation(key)
      end
    end

    def clear_database
      collection.drop
    end

    private

    def collection; @collection; end
  end
end

app/controllers/go_translate_yourself/site_translations_controller.rb
module GoTranslateYourself
  class SiteTranslationsController < ApplicationController
    before_filter :auth
    helper 'go_translate_yourself/translation_tabs'
    helper 'go_translate_yourself/translation_table'

    def edit
      @translations = hash_class[
        *GoTranslateYourself.current_store.keys_without_prefix.collect do |key| 
          [key, GoTranslateYourself.current_store.default_translation("dev.#{key}")]
        end.flatten
      ]
      # NOTE: This is not your typical ruby-esque way to do things, what with the passing by reference,
      # but it totally works.  I'm getting a nested hash of the namespaces.
      @translations_split = {}
      @translations.each do |key, default_translation|
        tran_parts = key.split('.')
        current_position = @translations_split
        while tran_parts.length > 1
          next_part = tran_parts.shift
          unless current_position[next_part]
            current_position[next_part] = {}
          end
          current_position = current_position[next_part]
        end
        current_position[tran_parts.first] = key
      end
      @locales = GoTranslateYourself.locales
      render :layout => GoTranslateYourself.layout_name
    end

    def update
      if params[:translations] && !params[:translations].empty?
        params[:translations].each do |key, value|
          I18n.backend.store_translations(key.to_sym, value)
        end
      end
      redirect_to site_translations_path
    end

    private

    def auth
      GoTranslateYourself.auth_handler.bind(self).call if GoTranslateYourself.auth_handler.is_a? Proc
    end

    def hash_class
      RUBY_VERSION < '1.9' ? ActiveSupport::OrderedHash : Hash
    end
  end
end

app/helpers/go_translate_yourself/site_translations_helper.rb
module GoTranslateYourself
  module SiteTranslationsHelper
    def translation_text_field(locale, key, default_translation)
      key_parts = key.split('.').inject('') do |kp, key_part|
        kp << "[#{key_part}]"
      end
      translation_text = begin
        I18n.t!(key, :locale => locale)
      rescue I18n::ArgumentError
        GoTranslateYourself.current_store.default_translation("dev.#{key}")[1..-2]
      end
      text_field_tag("translations[#{locale}]#{key_parts}",
                     translation_text || "",
                     :size => (default_translation.size))
    end
  end
end

app/helpers/go_translate_yourself/translation_table_helper.rb
module GoTranslateYourself
  module TranslationTableHelper
    def translation_table_for(translations, locales)
      render :partial => 'go_translate_yourself/site_translations/translation_table', :locals => { :translations => translations, :locales => locales }
    end

    def get_translations_under(child, translations)
      array_representation = translations.select{|k, v| child.values.include?(k)}
      hash_var = HashFromArray.hash_from_array(array_representation)
    end
  end
end

app/helpers/go_translate_yourself/translation_tabs_helper.rb
module GoTranslateYourself
  module TranslationTabsHelper
    def tabs_for(hash)
      render :partial => 'go_translate_yourself/site_translations/tabs', :locals => { :hash => hash }
    end

    def tabs_full_for(hash)
      render :partial => 'go_translate_yourself/site_translations/tabs_full', :locals => { :hash => hash }
    end
  end
end

app/views/go_translate_yourself/site_translations/_tabs.html.erb
<% id = "tabs-#{hash.object_id}" -%>
<div id=<%= id -%>>
  <ul>
    <% hash.each do |key, child| %>
      <li><a href="#tabs-<%= hash.object_id -%>-<%= key.object_id -%>"><%= key -%></a></li>
    <% end %>
  </ul>
  <% hash.each do |key, child| %>
    <% child_translations = get_translations_under(child, @translations) -%>
    <% child_hash_array_representation = child.select{|k, v| v.is_a?(Hash) } -%>
    <div id="tabs-<%= hash.object_id -%>-<%= key.object_id -%>">
      <%= translation_table_for(child_translations, @locales) -%>
      <% unless child_hash_array_representation.empty? -%>
        <%= tabs_for(HashFromArray.hash_from_array(child_hash_array_representation)) -%>
      <% end -%>
    </div>
  <% end %>
</div>
<script>
  $(function() {
    $('#<%= id -%>').tabs();
  });
</script>

app/views/go_translate_yourself/site_translations/_tabs_full.html.erb
<% hash.each do |key, child| %>
  <h3><%= key -%></h3>
  <% child_translations = get_translations_under(child, @translations) -%>
  <% child_hash_array_representation = child.select{|k, v| v.is_a?(Hash) } -%>
  <% child_hash = HashFromArray.hash_from_array(child_hash_array_representation) -%>
  <%= tabs_full_for(child_hash) -%>
  <%= translation_table_for(child_translations, @locales) -%>
<% end %>

app/views/go_translate_yourself/site_translations/_translation_table.html.erb
<table class="gt_site_translations">
  <tr class="gt_ths">
    <th>Key</th>
    <th>Value</th>
  </tr>
  <% translations.each do |key, default_translation| %>
    <tr class="gt_separator">
      <td colspan="2"></td>
    </tr>
    <tr class="gt_default_value">
      <td class="gt_key">
        <%= key %>
      </td>
      <td class="gt_value">
        <%= default_translation %>
      </td>
      <% locales.each do |locale| %>
        <tr>
          <td>
            <%= locale %>
          </td>
          <td>
            <%= translation_text_field locale, key, default_translation %>
          </td>
        </tr>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/go_translate_yourself/site_translations/edit.html.erb
<h2>Translations Editor</h2>
<%= form_tag update_site_translations_path, :method => :post do %>
  <%= tabs_for(@translations_split) -%>
  <%= submit_tag "Save" %>
<% end %>